[req]
distinguished_name = dn
prompt             = no

[dn]
C  = GR
ST = Athens
L  = Attica
O  = GRNET
CN = GRNET Wallet Backend Signer

[v3]
basicConstraints       = critical, CA:FALSE
keyUsage               = critical, digitalSignature
extendedKeyUsage       = clientAuth,codeSigning
subjectKeyIdentifier   = hash
